### ISSUE TITLE
not available through npm

### ISSUE THREAD

**Issue by salmanbukharihitori** [SystangoTechnologies/react-native-apple-sign-in#1]
Is this package available through npm because when we install using the command given, we get the following error

npm ERR! code E404
npm ERR! 404 Not Found: react-native-apple-sign-in@latest

**Comment by salmanbukharihitori** [comment]
I tried installing after cloning from the repo, but there are errors all over the place. does this even work?

**Comment by amourya-systango** [comment]
Yes it is available on npm please find it from the following link:
https://www.npmjs.com/package/@jonstuebe/react-native-apple-sign-in

Someone has published this on npm by forking it from my github repo as you can see below:
https://github.com/jonstuebe/react-native-apple-sign-in#readme

but for now I'll suggest to take it from my repo directly as you can add "react-native-apple-sign-in": `https://github.com/SystangoTechnologies/react-native-apple-sign-in.git` in your package.json file to install it.

**Comment by tux2nicolae** [comment]
Is there any difference between these two repository?

https://github.com/SystangoTechnologies/react-native-apple-sign-in
https://github.com/SystangoTechnologies/react-native-apple-authentication

The react-native-apple-authentication it's also available on npm too under
https://www.npmjs.com/package/react-native-apple-authentication

**Comment by ramazanarslan** [comment]
@tux2nicolae    
i am using like this   
`"react-native-apple-sign-in": "git+https://github.com/SystangoTechnologies/react-native-apple-sign-in.git",`

**Comment by raizal** [comment]
Successfully add the libs by using
`yarn add SystangoTechnologies/react-native-apple-sign-in`

**Comment by amourya-systango** [comment]
Please use the following as this lib has been deprecated and will be removed soon. 
https://github.com/SystangoTechnologies/react-native-apple-authentication
