### ISSUE TITLE
Getting All keys null

### ISSUE THREAD

**Issue by shoryavaish** [SystangoTechnologies/react-native-apple-sign-in#4]
authorizationCode: null
authorizedScopes: []
email: null
fullName: null
identityToken: null
realUserStatus: 1
state: null
user: "some_value" // this is not null

**Comment by arunkmoury** [comment]
Same here, I also verified the private email relay

**Comment by amourya-systango** [comment]
We are checking this. Stay tuned :)

**Comment by gusma296** [comment]
same problem here

**Comment by 431910864** [comment]
NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];

**Comment by iba-ragi** [comment]
> ```
> NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> ```

Thank you.
I fixed it!

**Comment by iba-ragi** [comment]
`node_modules/react-native-apple-authentication/ios/AppleAuthentication.m`

I replaced this file with https://github.com/NichAga/react-native-apple-authentication/blob/d15cce8edc1bbd304c39de7a3404529300d65671/ios/AppleAuthentication.m

I could get other values.

**Comment by 431910864** [comment]
> `node_modules/react-native-apple-authentication/ios/AppleAuthentication.m`
> 
> I replaced this file with https://github.com/NichAga/react-native-apple-authentication/blob/d15cce8edc1bbd304c39de7a3404529300d65671/ios/AppleAuthentication.m
> 
> I could get other values.

good

**Comment by amourya-systango** [comment]
@iba-ragi could you please create a PR of your changes?

**Comment by gusma296** [comment]
> ```
> NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> ```

thanks this is work for me, please @amourya-systango update lib for this issue thanks

**Comment by shoryavaish** [comment]
> > ```
> > NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> > ```
> 
> thanks this is work for me, please @amourya-systango update lib for this issue thanks

After adding this not getting email and fullname keys.
Maybe there is an issue of scope. Not asking for permission while signing.

**Comment by gusma296** [comment]
> > > ```
> > > NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> > > ```
> > 
> > 
> > thanks this is work for me, please @amourya-systango update lib for this issue thanks
> 
> After adding this not getting email and fullname keys.
> Maybe there is an issue of scope. Not asking for permission while signing.

check this https://forums.developer.apple.com/thread/121496#379297

**Comment by shoryavaish** [comment]
> > > > ```
> > > > NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> > > > ```
> > > 
> > > 
> > > thanks this is work for me, please @amourya-systango update lib for this issue thanks
> > 
> > 
> > After adding this not getting email and fullname keys.
> > Maybe there is an issue of scope. Not asking for permission while signing.
> 
> check this https://forums.developer.apple.com/thread/121496#379297

I checked this but I tried in another device also, didn't ask for permissions.

**Comment by iba-ragi** [comment]
we can get name and email.

check [here](https://github.com/SystangoTechnologies/react-native-apple-authentication/issues/6#issuecomment-564379312)

**Comment by Estebank94** [comment]
> ```
> NSString *identityToken = [[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding];
> ```

Where do I have to put this?

**Comment by leitdeux** [comment]
@Estebank94 Check out the changes to the method below, found in `AppleAuthentication.m`:

By the way, it turns out we also need to de-structure `fullName` to get access to `givenName` and `familyName`, and we need to encode the `authenticationCode` string as well:

```objective-c
- (void)authorizationController:(ASAuthorizationController *)controller
   didCompleteWithAuthorization:(ASAuthorization *)authorization  API_AVAILABLE(ios(13.0))
{
  ASAuthorizationAppleIDCredential* credential = authorization.credential;

  NSDictionary* user = @{
    @"familyName":RCTNullIfNil(credential.fullName.familyName),
    @"givenName": RCTNullIfNil(credential.fullName.givenName),
    @"email": RCTNullIfNil(credential.email),
    @"user": credential.user,
    @"authorizedScopes": credential.authorizedScopes,
    @"realUserStatus": @(credential.realUserStatus),
    @"state": RCTNullIfNil(credential.state),
    @"authorizationCode": RCTNullIfNil([[NSString alloc]initWithData:credential.authorizationCode encoding:NSUTF8StringEncoding]),
    @"identityToken": RCTNullIfNil([[NSString alloc]initWithData:credential.identityToken encoding:NSUTF8StringEncoding])
  };

  _promiseResolve(user);
}
```

**Comment by amourya-systango** [comment]
Please use the following as this lib has been deprecated and will be removed soon. 
https://github.com/SystangoTechnologies/react-native-apple-authentication
