### ISSUE TITLE
"RNCSignInWithAppleButton" was not found in the UIManager.

### ISSUE THREAD

**Issue by Hashir524** [SystangoTechnologies/react-native-apple-sign-in#5]
Can you please help me with the setup. It would be much appreciated.

**Comment by Hashir524** [comment]
I manually linked it with Project. What am i missing here?

**Comment by amourya-systango** [comment]
Could you please check it again?

**Comment by mpargar** [comment]
Same problem here w/ the version 0.6 but in my case was autolinked. (Excuse my english).
![image](https://user-images.githubusercontent.com/32663960/70192332-a5d1b900-16b8-11ea-829d-ac9f632f7af8.png)

**Comment by DungBuiDeveloper** [comment]
same problem

**Comment by PradoGuilherme** [comment]
Hey @DungBuiDeveloper, @mpargar, @Hashir524, @amourya-systango!
Did you guys made react-native link react-native-apple-authentication? And after pod install on iOS folder?

**Comment by Estebank94** [comment]
Same problem on rn 0.61.4 with auto linking

**Comment by Estebank94** [comment]
I fixed the problem by adding 

`pod 'react-native-apple-sign-in', :path => "../node_modules/react-native-apple-sign-in/react-native-apple-sign-in.podspec"`

Inside the podfile

**Comment by amourya-systango** [comment]
Please use the following as this lib has been deprecated and will be removed soon. 
https://github.com/SystangoTechnologies/react-native-apple-authentication
