### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by tux2nicolae** [SystangoTechnologies/react-native-apple-sign-in#6]
Hi,

Would be awesome for this repository to have a licence file to clarify the rights to use.

Best regards,
Nicolae

**Comment by amourya-systango** [comment]
Yes, we are working on it. We will add it soon.

**Comment by michaelflowers** [comment]
Hi @amourya-systango 

Is there any news on this?

The package.json says its MIT but is missing the licence file.

Cheers

**Comment by amourya-systango** [comment]
Please use the following as this lib has been deprecated and will be removed soon. 
https://github.com/SystangoTechnologies/react-native-apple-authentication
