### ISSUE TITLE
I can't open the app with version 12 and below, it is crashing.

### ISSUE THREAD

**Issue by ramazanarslan** [SystangoTechnologies/react-native-apple-sign-in#8]
Hi , I know `Sign in with Apple` only works version 13 or above.  But it is crashing when i run with version 12 or below simulator.  

``` 
 render() {
    const majorVersionIOS = parseInt(Platform.Version, 10);
    if (majorVersionIOS <= 12) return null;
    return <View>{SignInWithAppleButton(styles.appleBtn, this.appleSignIn)}</View>;
  }
```

i checked version number, it should return. but some native errors 

By the way, i realized that, just adding the pod, also gives me the same error.

this error occurs on iPhone 7 Simulator, version 12.4 
![image](https://user-images.githubusercontent.com/31334024/70381484-2106c980-195c-11ea-8f5c-edf066a6319b.png)

   "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-apple-sign-in": "git+https://github.com/SystangoTechnologies/react-native-apple-sign-in.git",

**Comment by amourya-systango** [comment]
Please use the following as this lib has been deprecated and will be removed soon. 
https://github.com/SystangoTechnologies/react-native-apple-authentication
